# -*- coding: utf-8 -*-
"""Aerofit_case_study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/rathika0706/Aerofit-Treadmill-Sales-Analysis-using-Descriptive-Statistics-and-Probability/blob/main/Aerofit_case_study.ipynb

# Aerofit Treadmill Case Study using Descriptive Statistics and Probability

1.Importing the important libraries for data exploration and visualization.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""2.Reading the dataset and observations on shape of data, data types of all attributes and statistical summary"""

data=pd.read_csv("aerofit_treadmill.csv")

data.head()

data.shape

"""Aerofit dataset contains 180 rows and 9 columns"""

data.info()

"""From the above output we observe that there are no missing values and we are provided with cleaned data set. Lets explore the data and use probability and descritpive statistics to get business insights."""

data.describe()

"""The above result gives statistical summary about the data. We also observe that dataset includes people betweeen the age group of 18-50 years. Education of people lies between 12 years and 21 years.Income of people lies between 29,562 dollars and 1,04,581 dollars.

3.Non-Graphical analysis:Value counts and unique attributes.
"""

data["Product"].value_counts()

"""We observe that, dataset contains three products KP281,KP481,KP781"""

data["Gender"].value_counts()

"""From the above result, we observe that there are more number of male users compared to females."""

data["MaritalStatus"].value_counts()

"""We observe that couples purchased more treadmills compared to Singles."""

data["Fitness"].value_counts()

"""We observe that most of the customers who purchase treadmills fall under fitness scale of 3.

4.Visual analysis- Univariate and bivariate
"""

sns.histplot(data["Age"],bins=5)
plt.title("No.of products purchased across different age groups")
plt.show()

"""From the above histogram, we observe that age group between 24 and 32 have purchased more products and the second age group between 18 and 24. Hence the targeted customers fall under age group between 18 and 35."""

sns.countplot(x="Product",hue="Gender",data=data)
plt.xlabel("Product")
plt.ylabel("Count")
plt.title("Frequency of Products purchase ")
plt.show()

"""We observe that customers purchased KP281 more times compared to other products and KP781 product is less purchased by females compared to males."""

x_var=data["Gender"].value_counts().index
y_var=data["Gender"].value_counts().values
plt.bar(x_var,y_var)
plt.xlabel("Gender")
plt.ylabel("Count")
plt.title("Frequency of Products purchase across Gender")
plt.show()

"""we observe that there are more number of male customers  compared to females"""

sns.histplot(data["Income"],bins=10)
plt.title("No.of customers across Income groups")
plt.show()

"""We observe that more number of customers are from income group between 30k to 65k dollars."""

sns.kdeplot(data["Education"])
plt.title("Products purchased across years of education groups")
plt.show()

"""We observe that between 12 and 18 years of education groups, products have been purchased"""

sns.boxplot(y=data["Miles"])
plt.title("Boxplot showing miles and its outliers")
plt.show()

"""From the above boxplot, we observe that average miles customers walk on treadmill is 103 and there are some outliers where customers walk beyond maximum miles."""

sns.boxplot(y=data["Usage"])
plt.title("Boxplot showing usage of treadmills and its outliers")
plt.show()

"""The above boxplot shows average usage of treadmill in a week to be 3.4 times and  two outliers are found to use it 6/7 times in a week."""

sns.heatmap(data.corr(),annot=True,cmap="Blues")

"""The above heatmap gives correlaiton of the different attributes.

Insights from heat map:



*   Eductaion is highly correlated with income as its obvious. It also has impact on product purchased. Eductation also have significatnt correlation between fitness rating and Usage of the treadmill.
*   Usage is extremely correlated with Fitness and Miles and has a higher correlation with Income and Education as well.

*   Income is highly correlated with Product and Education. It also had good correlation with Age, usage, Fitness, Miles.
*   From above we can say that Product is extremely correlated with Income, Education, Fitness, Usage along with Miles.

*   We can say that Age and Education are indicator of Income which affect the product bought. The more advance the Product is the more its Usage and hence more the miles run which result into improved Fitness rating.

5.Descriptive satistics and Probabilities using Contingency tables
"""

#Contingency tables
pd.crosstab(index=data["Product"],
            columns=data["Gender"],
            margins=True)

"""From the above contingency table we can answer various questions on marginal and conditional probabilities.
The following questions are answered by using contingency table
"""

#What is the probability of customers buying KP281 treadmill?
80/180

#What is the probability of customers buying KP481 treadmill?
60/180

#What is the probability of customers buying KP781 treadmill?
40/180

#What is the probability of male customers buying any kind of treadmill?
104/180

#What is the probability of female customers buying any kind of treadmill?
76/180

#What is the probability of a male customer buying a KP781 treadmill?
33/180

#What is the probability of a female customer buying a KP781 treadmill?
7/180

#What is the probability of a female customer buying a KP481 treadmill?
29/180

#What is the probability of a male customer buying a KP481 treadmill?
31/180

#What is the probability of a male customer buying a KP281 treadmill?
40/180

#What is the probability of a female customer buying a KP281 treadmill?
40/180

"""From the above questions we observe that there is an equal chance of selling KP281 treadmill to both males and females, whereas KP781 treadmill should be targeted towards male customers as there is less probabilty for female customers."""

pd.crosstab(index=data["Product"],
            columns=data["MaritalStatus"],
            margins=True)

#What is the probability of partnered people buying KP281 treadmill?
48/180

#What is the probability of single people buying KP281 treadmill?
32/180

#What is the probability of partnered people buying KP481 treadmill?
36/180

#What is the probability of single people buying KP481 treadmill?
24/180

#What is the probability of partnered people buying KP781 treadmill?
23/180

#What is the probability of single people buying KP781 treadmill?
17/180

pd.crosstab(index=data["Product"],
            columns=data["Fitness"],
            margins=True)

"""The above contingency table gives an overview about fitness scale of 1 to 5 with 1 being poor shape, 2-fair shape, 3-good shape, 4-very good shape and 5 being excellent shape. It also shows that there is zero possibility of customers who are in excellent shape buying KP481."""

#What is the probability of  most bought treadmill by customers who are in excellent shape?
print("KP281:",2/180)
print("KP481:",0/180)
print("KP781:",29/180)

"""The above result shows that there is high probability of 0.16 of customers who are in excellent shape buying KP781 treadmill"""

#what is the probaility of customers who are in good shape?
97/180

"""The above result shows that more customers fall under fitness sacle of 3 which os good shape"""

#What is the probabiltity of customer in good shape buyiing KP281, KP481 KP781 treadmill?
print("KP281:",54/180)
print("KP481:",39/180)
print("KP781:",4/180)

"""The above result shows that customers in good shape prefer buying KP281 treadmill with probability of 0.3

**Customer Profiling**

1.   KP281 Treadmill:



  

*   Age = 20 to 40 years
*   Education Level = 14 & 16 years above.

*   Annual Income = Below $70,000
*   Fitness Rating = 2 & 3


*   Usage = 2 to 4 times in each week
*   Miles = Below 150 miles the customer expects to walk/run each week


2.   KP481 treadmill:



  

*   Age = 20 to 40 years
*   Education Level = 14 & 16 years above.

*   Annual Income = Below $70,000
*   Fitness Rating = 2,3&4


*   Usage = 2 to 4 times in each week
*   Miles = Below 150 miles the customer expects to walk/run each week
3.   KP781 treadmill:



  

*   Age = 20 above
*   Education Level = 18 years above.

*   Annual Income = Above $45,000
*   Fitness Rating = 4&5


*   Usage = 4 to 6 times in each week
*   Miles = Above 150 miles the customer expects to walk/run each week

**Recommendations:**

1.Aerofit should promote KP784 model to the person whose annual income is in between 40,000 to 60,000. As combine sales numbers of all 3 models are excellent in this income range and some customer from this income range already bought KP784. So it seems there is good potential to push premium series treadmill.

2.There is huge sales gap for KP784 model i.e. only 18% of total sale of KP781 is sold to Female. To increase this number we should give some offers and trials for females.

3.Aerofit should create some awareness reagarding health and product specifically for the person with 15, 20, 21 years of education level. As there is correlation between education and income and we can see there are people with 14 years of education level bought 11 times more machine (55 machines) as compare to level 15 (5 machines).

4.Aerofit should promote KP784 model to the person who are going to use treadmill 3 times in each week. As people buying good number of KP284 & KP484 who are going to use it for 3 times. We can push by giving trials of our premium model as it has more feature and that will give added advantages to buyer.
"""